-- Add new ShopCategory enum values
ALTER TYPE "ShopCategory" ADD VALUE IF NOT EXISTS 'SUPERMARKET';
ALTER TYPE "ShopCategory" ADD VALUE IF NOT EXISTS 'FASHION_ACCESSORIES';
ALTER TYPE "ShopCategory" ADD VALUE IF NOT EXISTS 'MOBILE_PHONES';
ALTER TYPE "ShopCategory" ADD VALUE IF NOT EXISTS 'ELECTRONICS';
ALTER TYPE "ShopCategory" ADD VALUE IF NOT EXISTS 'SALON';
ALTER TYPE "ShopCategory" ADD VALUE IF NOT EXISTS 'FOOD_BEVERAGE';
ALTER TYPE "ShopCategory" ADD VALUE IF NOT EXISTS 'STATIONERY';
ALTER TYPE "ShopCategory" ADD VALUE IF NOT EXISTS 'FURNITURE';
ALTER TYPE "ShopCategory" ADD VALUE IF NOT EXISTS 'JEWELLERY';
